services:
  starbound-server:
    image: ghcr.io/mercujerry/starbound-ds-docker:main
    container_name: starbound
    environment:
      - STEAM_ACCOUNT=<steamaccountname>
      - STEAM_PASSWORD=<steampassword>
      - MOD_IDS=()
      - PUID=1000
      - SKIP_INSTALL=false # change to skip install
    volumes:
      - /path/to/folder:/starbound
    ports:
      - 21025:21025/tcp #default game port
    restart: unless-stopped